version: '3'

services:

    redis:
      image: redis
      container_name: bot_redis
      ports:
          - 6379:6379
      volumes:
      - ./docker/redis:/data
      - ./docker/redis.conf:/etc/redis/redis.conf

    mysql:
      image: mysql
      environment:
          - MYSQL_ROOT_PASSWORD=password
      ports:
          - 3306:3306
      volumes:
        - ./docker/store:/var/lib/mysql
